### ISSUE TITLE
Cannot find npm cache on GitHub actions

### ISSUE THREAD

**Issue by ianwolson** [mujo-code/puppeteer-headful#130]
Hello, I am running into an issue trying to get this to work with my project.

It seems to fail on the "Install Dependencies" step, and therefore the extension cannot be built and the tests fail.
The "Install Dependency" step fails due to it not finding the npm cache.

Is there something I am doing wrong? Here is the error and my .yml file.

Run actions/setup-node@v3
  with:
    node-version: 18.x
    cache: npm
    always-auth: false
    check-latest: false
    token: ***
  env:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
Found in cache @ /opt/hostedtoolcache/node/18.16.0/x64
Environment details
  node: v18.16.0
  npm: 9.5.1
  yarn: 1.[2](https://github.com/amida-tech/hyperpop/actions/runs/5292948209/jobs/9580454181?pr=411#step:4:2)2.19
/opt/hostedtoolcache/node/18.16.0/x6[4](https://github.com/amida-tech/hyperpop/actions/runs/5292948209/jobs/9580454181?pr=411#step:4:4)/bin/npm config get cache
/home/runner/.npm
**npm cache is not found**

[test.txt](https://github.com/mujo-code/puppeteer-headful/files/11773186/test.txt)

**Comment by amaurypichat** [comment]
Hi,did you succeed ?

**Comment by ianwolson** [comment]
Yes, one day it just started working with no explanation.  Very bizarre issue.
