### ISSUE TITLE
It's possible to see the launched chrome in docker? 

### ISSUE THREAD

**Issue by imjeen** [mujo-code/puppeteer-headful#29]
I'm trying to run all the code in docker, include the puppeteer with chrome, and  just for local development. here is my steps below：

1. `docker build -t chrome .`
2. `docker run --rm -it -w /app  -v $PWD:/app  chrome  bash`,  
3. `npm i puppeteer -S` and `node ./index.js`, code see blow:

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({
        headless: false, // open the  chrome
        executablePath: "/usr/bin/google-chrome-stable", // process.env.PUPPETEER_EXEC_PATH 
        args: [
            '--no-sandbox', 
            '--disable-setuid-sandbox',
        ]
    });
    const page = await browser.newPage();
    await page.goto('https://google.com', { waitUntil: 'networkidle2' });

    console.log('hold it for a while and see the launched chrome...');
    await page.waitFor(20000);

    await browser.close();

})();
```
Finally, it turns out ok, but I cannot see the launched chrome in docker. 

If it's possible to see the launched chrome from docker, It will be convenient to develop something useful.

**Comment by stefanbuck** [comment]
I never thought about that, but it seems to be possible https://medium.com/@SaravSun/running-gui-applications-inside-docker-containers-83d65c0db110. Out of interest, what's the reason why you want to run everything within docker?

**Comment by imjeen** [comment]
Thanks for your answer.

There are many and different projects in my team, and we are trying to Dockerize our applications. you know, all the dependencies of the application which would assist it to run in any environment, everyone will be benefit from the docker.

At last, I found the [VNC](https://en.wikipedia.org/wiki/Virtual_Network_Computing)  can be used to show the GUI for container. 

[Running Chrome in a Docker container](https://medium.com/dot-debug/running-chrome-in-a-docker-container-a55e7f4da4a8)

**Comment by jcblw** [comment]
Thanks for the question @imjeen. Closing because it seems you were able to find a solution.
