### ISSUE TITLE
Marketplace shows 12.3.1 as latest version

### ISSUE THREAD

**Issue by ianschmitz** [mujo-code/puppeteer-headful#84]
https://github.com/marketplace/actions/puppeteer-headful

This caught us since this old version uses Node 12, where as the `v2` tag uses Node 16. I wonder if we could delete the `12.3.1` tag and maybe the marketplace will pick up `v2` as latest? Not sure if this would break existing workflows...

https://github.com/mujo-code/puppeteer-headful/tags

**Comment by jcblw** [comment]
Sorry not sure why v2 is in the tags published 16.6.0 tag to match the node version running. Closing this ticket, please let me know if you have any further issues.
