### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by maufrontier** [mujo-code/puppeteer-headful#88]
Hey folks!

Great job on this action, it's super helpful 👍

I see this has 23 forks already, but I don't see a license file. Is this meant to be proprietary code or Open Source?

It would be great if you could add a license file so everyone who wants to fork it and make contributions knows whether they can legally do so or not 🙂.

Cheers!

**Comment by jcblw** [comment]
Added! Thanks for calling this out.

https://github.com/mujo-code/puppeteer-headful/commit/264e32942c5975b58d4153189b73bdf89405d7f7

**Comment by maufrontier** [comment]
Fantastic! Thanks for the quick response and for sharing your work! 😊🙌
